apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx-health
  namespace: ingress
spec:
  type: ClusterIP
  selector:
    name: nginx-ingress-microk8s
  ports:
    - name: healthz
      port: 10254
      targetPort: 10254
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-healthz-ingress
  namespace: ingress
spec:
  ingressClassName: public
  tls:
  - hosts:
    - nginx.medisample.online
  secretName: microbot-ingress-nginx-tls
  rules:
    - host: nginx.medisample.online
      http:
        paths:
          - path: /healthz
            pathType: Prefix
            backend:
              service:
                name: ingress-nginx-health
                port:
                  number: 10254